import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase configuration options for this app.
///
/// This file is typically generated by the FlutterFire CLI:
/// `flutterfire configure`
///
/// Replace the placeholder values below with your Firebase project settings.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBInb2K2dMMRZBDlpVt6OMR60lu1Hx8XuI',
    appId: '1:841248185002:web:fbbbf58ec2834204b48ed3',
    messagingSenderId: '841248185002',
    projectId: 'proserve-hub-ada0e',
    authDomain: 'proserve-hub-ada0e.firebaseapp.com',
    storageBucket: 'proserve-hub-ada0e.firebasestorage.app',
    measurementId: 'G-FW2817GF7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUY2-ys3k4-hB7pgJyjpJsLQCDPTmIrN0',
    appId: '1:841248185002:android:d6aa63d9a0a982f2b48ed3',
    messagingSenderId: '841248185002',
    projectId: 'proserve-hub-ada0e',
    storageBucket: 'proserve-hub-ada0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4xWmnUNWCq4vLxi1TlzDraeNfPrNljEo',
    appId: '1:841248185002:ios:2b2b6b19a537dd6fb48ed3',
    messagingSenderId: '841248185002',
    projectId: 'proserve-hub-ada0e',
    storageBucket: 'proserve-hub-ada0e.firebasestorage.app',
    iosBundleId: 'com.proservehub.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4xWmnUNWCq4vLxi1TlzDraeNfPrNljEo',
    appId: '1:841248185002:ios:2b2b6b19a537dd6fb48ed3',
    messagingSenderId: '841248185002',
    projectId: 'proserve-hub-ada0e',
    storageBucket: 'proserve-hub-ada0e.firebasestorage.app',
    iosBundleId: 'com.proservehub.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBInb2K2dMMRZBDlpVt6OMR60lu1Hx8XuI',
    appId: '1:841248185002:web:9d07112d7e864860b48ed3',
    messagingSenderId: '841248185002',
    projectId: 'proserve-hub-ada0e',
    authDomain: 'proserve-hub-ada0e.firebaseapp.com',
    storageBucket: 'proserve-hub-ada0e.firebasestorage.app',
    measurementId: 'G-F1BMM68VWZ',
  );

  static FirebaseOptions get linux => throw UnsupportedError(
    'Linux is not supported. Please run flutterfire configure to add Linux support.',
  );
}
